server: 
  port: 8080
spring:
 datasource:
  driverClassName: org.gjt.mm.mysql.Driver
  url : jdbc:://localhost:5432/teste?charSet=LATIN1
  username : root
  password : 123123
 jpa :
  database-platform : org.hibernate.dialect.PostgreSQLDialect
  show-sql : false
  hibernate:
   ddl-auto : create